### ISSUE TITLE
Templates cache is never refreshed

### ISSUE THREAD

**Issue by slemarchand** [yasuflatland-lf/damascus#4]
Templates cache is never refreshed : if you build and install a new version of Damascus with modifications in template files, the template files stored in `${HOME}/.damascus/templates` are never updated.

**Comment by yasuflatland-lf** [comment]
Hi @slemarchand 

Thank you for finding this issue. I want to discuss how to resolve this with you guys. Let's get @AndyWu2015 in this loop too.

The solution what I came up with was delete template folder in /installers/global shell, but I'm wondering if it's right way because,

1. If Damascus would be integrated with Blade, Blade will take care of upgrade. In that case, depending on the design of Blade, Damascus may need to cleanup code in the code rather than shell (installer).
2. Assuming Damascus will be integrated with Blade, Blade has just moved onto using installer instead of the shell installation. I assume it'd be easier to leave the all upgrade / install staff to installer instead of that Damascus takes care of everything on it's own.
3. In case of implementing upgrade tool in Damascus, we also need to consider how to detect if it's in the installation process and version different of templates, e.g., which is bit pain in the neck.

Let me know you guys thought.

**Comment by slemarchand** [comment]
My preferred approach is to implement templates cache update in Damascus (I have just submitted  [a pull request](https://github.com/yasuflatland-lf/damascus/pull/5)). 

I have implemented templates changes detection using a build number property in `~/.damascus/settings.properties` file. 

Another possibility, more pragmatic,  would have been to copy the templates into the directory `~/.damascus/templates` each time the command `damascus` is launched, because the copy is very fast !

**Comment by yasuflatland-lf** [comment]
Hi @slemarchand 
Wow, you are very quick! Let me take a look. Yeah, as you said, the copy is very first so should be OK with that way too. 

Another point where I didn't want to overwrite every time was in an actual project, sometimes I wanted to tweak some code temporally specifically for the project and it was pretty useful. (I may need to introduce this idea public on wiki or README.md). Given that, it sounds good to me that your current PR way, updating templates only when version is changed.

**Comment by AndyWu2015** [comment]
sorry for the late replay ,  we haven't discussed the detail of integrating damascus in to blade , so feel free to do want would be good for current usage.

**Comment by yasuflatland-lf** [comment]
@AndyWu2015 
Ok, thank you for your feedback!
